// Generated by CoffeeScript 1.7.1
var Singleton, compareFunction, dictionarySort, prompts, rl, userInterface, util, wordRequester;

util = require('util');

rl = require('readline');

prompts = rl.createInterface({
  input: process.stdin,
  output: process.stdout
});

Singleton = {
  word_holder: []
};

compareFunction = function(x, y) {
  if (x.toLowerCase() < y.toLowerCase()) {
    return -1;
  }
  if (x.toLowerCase() > y.toLowerCase()) {
    return 1;
  }
  return 0;
};

dictionarySort = function(arr) {
  return arr.sort(compareFunction);
};

wordRequester = function() {
  return prompts.question("Type a word: ", function(word) {
    var sortedWords, _i, _len;
    if (word) {
      console.log("You've added: " + word);
      Singleton.word_holder.push(word);
      return wordRequester();
    } else if (word === "") {
      sortedWords = dictionarySort(Singleton.word_holder);
      console.log("\nCongratulations! Your dictionary has " + sortedWords.length + " words:");
      for (_i = 0, _len = sortedWords.length; _i < _len; _i++) {
        word = sortedWords[_i];
        console.log("" + word);
      }
      return process.exit();
    } else {
      return console.log("Here we are");
    }
  });
};

userInterface = function() {
  console.log("Welcome to Word Sorter\n");
  return wordRequester();
};

userInterface();
