// Generated by CoffeeScript 1.7.1
var grandmaEngine, grandmaResponse, prompts, rl, util;

util = require('util');

rl = require('readline');

prompts = rl.createInterface({
  input: process.stdin,
  output: process.stdout
});

grandmaResponse = function(user_input) {
  var inputCapitals;
  inputCapitals = user_input.toUpperCase();
  if (user_input === "") {
    return "*Grandma continues watching TV*";
  } else if (user_input === inputCapitals) {
    return "NOT SINCE 1987";
  } else {
    return "SPEAK UP SONNY!!!";
  }
};

grandmaEngine = function() {
  console.log("*****\nWelcome to Deaf Grandma\n*****");
  return prompts.question("Ask Grandma a question: ", function(ask) {
    if (ask) {
      console.log(grandmaResponse(ask));
      return grandmaEngine();
    } else if (ask === "") {
      console.log(grandmaResponse(ask));
      return process.exit();
    }
  });
};

grandmaEngine();
