// Generated by CoffeeScript 1.7.1
var getuserInput, grandmaEngine, grandmaResponse, titleScreen, util;

util = require('util');

grandmaResponse = function(user_input) {
  var inputCapitals, inputText;
  inputText = "" + user_input;
  inputCapitals = ("" + user_input).toUpperCase();
  if (inputText === "") {
    return console.log("*Grandma continues watching TV*");
  } else if (inputText === inputCapitals) {
    return console.log("NOT SINCE 1987");
  } else {
    return console.log("SPEAK UP SONNY!!!");
  }
};

titleScreen = function() {
  return console.log("*****\nWelcome to Deaf Grandma\n*****");
};

getuserInput = function() {
  process.stdin.setEncoding('utf8');
  process.stdin.resume();
  return process.stdin.on('data', function(text) {
    return text.toString().trim();
  });
};

grandmaEngine = function() {
  var counter, input, _results;
  counter = 0;
  titleScreen();
  _results = [];
  while (counter !== 2) {
    input = getUserInput();
    grandmaResponse(input);
    if (counter === 2) {
      process.exit();
    }
    if (input === "") {
      _results.push(counter += 1);
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

grandmaEngine();
